version: "3.5"

services:
  memorious-postgres:
    image: postgres:11.4
    volumes:
      - "memorius-postgres:/var/lib/postgresql/data"
#      - "./import:/import"
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: datastore

  memorius-redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "memorius-redis:/data"

  memorious-worker:
    image: opendataservices/oroi-scrape:latest
    command: memorious process
    volumes:
      - "memorious-data:/data"
    environment:
      MEMORIOUS_BASE_PATH: /data
      MEMORIOUS_CONFIG_PATH: /oroi-scrape/config
      MEMORIOUS_DEBUG: 'true'
      ARCHIVE_PATH: /data/archive
      REDIS_URL: redis://memorius-redis:6379/0
      MEMORIOUS_DATASTORE_URI: postgresql://datastore:datastore@memorius-postgres/datastore
    tmpfs:
      - "/tmp"

  django-postgres:
    image: postgres:11.4
    volumes:
      - "django-postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: django_db
      POSTGRES_PASSWORD: django_db
    restart: always
 
  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
    environment:
      discovery.type: single-node
    restart: always

  declaration_nav:
    image: opendataservices/open-register-of-interests:db-load
#    volumes:
#      - "./import:/import"
    environment:
      DATABASE_URL: postgresql://django_db:django_db@django-postgres/django_db
      ALLOWED_HOSTS: '.docker.opendataservices.uk0.bigv.io,localhost'
      DEBUG: 'False'
      ES_HOST: "elasticsearch:9200"
    tmpfs:
      - "/tmp"
    ports:
      - "80:8001"
      - "8001:8001"
    restart: always

volumes:
  memorius-postgres:
    driver: local
  memorius-redis:
    driver: local
  memorious-data:
    driver: local
  django-postgres:
    driver: local
  elasticsearch:
    driver: local

