version: "3.5"

services:
  memorious-postgres:
    image: postgres:11.8
    volumes:
      - "memorious-postgres:/var/lib/postgresql/data"
#      - "./import:/import"
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: datastore
    ports:
      # WARNING this binds to localhost with docker compose,
      # but on ALL interfaces with docker stack.
      - "127.0.0.1:5432:5432"

  memorious-redis:
    image: redis:6.0.4-alpine3.11
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "memorious-redis:/data"

  memorious-worker:
    image: opendataservices/oroi-scrape:latest
    command: memorious process
    volumes:
      - "memorious-data:/data"
    environment:
      MEMORIOUS_BASE_PATH: /data
      MEMORIOUS_CONFIG_PATH: /oroi-scrape/config
      MEMORIOUS_DEBUG: 'false'
      ARCHIVE_PATH: /data/archive
      REDIS_URL: redis://memorious-redis:6379/0
      MEMORIOUS_DATASTORE_URI: postgresql://datastore:datastore@memorious-postgres/datastore
    tmpfs:
      - "/tmp"
    deploy:
      replicas: 2

  django-postgres:
    image: postgres:11.8
    volumes:
      - "django-postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: django_db
      POSTGRES_PASSWORD: django_db
    restart: always
 
  elasticsearch:
    image: elasticsearch:7.7.1
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
    environment:
      discovery.type: single-node
    restart: always

  declaration_nav:
    image: opendataservices/open-register-of-interests:latest
    command: "sh -c '
      ./manage.py migrate &&
      gunicorn --workers 2 --bind 0.0.0.0:8001 oroi.wsgi:application
      '"
    working_dir: /code/oroi/
#    volumes:
#      - "./import:/import"
    environment:
      DATABASE_URL: postgresql://django_db:django_db@django-postgres/django_db
      ALLOWED_HOSTS: '.declared.info,.docker.opendataservices.uk0.bigv.io,.localhost'
      DEBUG: 'False'
      ES_HOST: "elasticsearch:9200"
    tmpfs:
      - "/tmp"
    ports:
      - "81:8001"
      - "8001:8001"
    restart: always

volumes:
  memorious-postgres:
    driver: local
  memorious-redis:
    driver: local
  memorious-data:
    driver: local
  django-postgres:
    driver: local
  elasticsearch:
    driver: local

