version: "3.5"

services:
  declaration_nav-load:
    image: opendataservices/open-register-of-interests:re-map
    working_dir: /code/oroi/
    #    command: "sh -c 'python manage.py load_scrape_data postgresql://datastore:datastore@memorious-postgres/datastore'"
    command: "sh -c '
      python manage.py load_scrape_data postgresql://datastore:datastore@memorious-postgres/datastore bristol_meetings ;
      python manage.py load_scrape_data postgresql://datastore:datastore@memorious-postgres/datastore bristol_register ;
      python manage.py load_scrape_data postgresql://datastore:datastore@memorious-postgres/datastore gla_register ;
      python manage.py load_scrape_data postgresql://datastore:datastore@memorious-postgres/datastore ukparl_groups ;
      python manage.py load_scrape_data postgresql://datastore:datastore@memorious-postgres/datastore gla_gifts ;
      python manage.py load_scrape_data postgresql://datastore:datastore@memorious-postgres/datastore ukparl_twfy'"
    environment:
      DATABASE_URL: postgresql://django_db:django_db@django-postgres/django_db
      ALLOWED_HOSTS: '.docker.opendataservices.uk0.bigv.io,localhost'
      DEBUG: 'False'
      ES_HOST: "elasticsearch:9200"
    tmpfs:
      - "/tmp"
    deploy:
      restart_policy:
        condition: none
